### ISSUE TITLE
Add support for start/end clipping

### ISSUE THREAD

**Issue by kevinduffey** [aldor007/mort#22]
Not sure if this is in there yet, but the ability to specify the start and end points, preferably multiple of them per video so you can clip out smaller bits of video would be very nice to have.

**Comment by aldor007** [comment]
Hi
You can get that behaviour by making [HTTP range requests](https://developer.mozilla.org/en-US/docs/Web/HTTP/Range_requests).HTTP partial requests are [supported](https://github.com/aldor007/mort/blob/master/tests-int/Range.Spec.js) by mort.
